variables:
- group: keyvault-variable-group
#  pfxLocation : $(system.DefaultWorkingDirectory)/cert.pfx

pool:
  vmimage: windows-latest

workspace:
    clean: all
    
steps:
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'Visual Studio Enterprise Subscription – MPN (90964ca6-bc75-4398-9fa2-75c890c373cf)'
      KeyVaultName: 'certs-keyvault-test'
      SecretsFilter: '*'
      RunAsPreJob: true

  - powershell: dotnet build ./src
    displayName: Build Source Code
    
  - powershell: |
      ./generatePfx.ps1 `
        -pfxString $(test-certificate) 
    env:
      pfxPassword : $(password) # Set as secret variable
    displayName: Generate PFX
    
  - powershell: |
      ./sign.ps1 `
        -pfxPath $(pfxLocation)
    env:
      pfxPassword : $(password) # Set as secret variable
    displayName: Sign DLLs and exe

  - publish:  $(Build.SourcesDirectory)\src\bin\Debug\netcoreapp2.2\CodeSigning-Demo.dll
    artifact: SignedDll
      
  - task: DeleteFiles@1
    inputs:
      contents: \*.pfx
